version: 0.0
os: linux
files:
    - source: .
      destination: /home/ec2-user/pelada
      file_exists_behavior: OVERWRITE
hooks:
    ApplicationStart:
        - location: _config/scripts/restart_api
          timeout: 300
          runas: root
