name: CI/CD Pipeline

on:
  push:
    branches: [main]
    
jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PREVIOUS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PREVIOUS }}
          aws-region: sa-east-1

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          # Assuming the Deployment Group is already setup
          aws deploy create-deployment \
            --application-name pelada-app \
            --deployment-group-name Pelada \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}